name: 本番環境へのデプロイ

on:
  push:
    branches:
      - master # `master`ブランチにプッシュされたとき

env:
  TZ: Asia/Tokyo
  NODE_ENV: production

jobs:
  deploy-prod:
    name: 本番環境へのデプロイ
    runs-on: ubuntu-latest

    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v4

      - name: Node.jsのセットアップ
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: ライブラリのインストール
        run: npm ci

      - name: ビルド
        run: npm run build

      - name: デプロイ
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy out --project-name=moyapoi-web
